ALTER TABLE "SubscriptionSetting"
ADD COLUMN "cardHolder" TEXT NOT NULL DEFAULT 'Abdunazarov Mardon',
ADD COLUMN "cardNumber" TEXT NOT NULL DEFAULT '9860 1201 0243 8112',
ADD COLUMN "cardType" TEXT NOT NULL DEFAULT 'HUMO',
ADD COLUMN "amount" INTEGER NOT NULL DEFAULT 119000;
